name: Docker Security Scan

on: [push]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t devsecops-app:${{ github.sha }} .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-app:${{ github.sha }}'
          format: 'table'
          [cite_start]exit-code: '1' # Hace que el pipeline falle si detecta algo grave [cite: 83]
          [cite_start]severity: 'CRITICAL,HIGH' [cite: 78]
